#pragma once

#include "Predefine.h"

NS_GLH_BEGIN

class Framebuffer
{
public:
    enum FramebufferTarget
    {
        FBT_DRAW_FRAMEBUFFER = GL_DRAW_FRAMEBUFFER,
        FBT_READ_FRAMEBUFFER = GL_READ_FRAMEBUFFER,
        FBT_FRAMEBUFFER = GL_FRAMEBUFFER,
    };

    enum FramebufferAttachment
    {
        FBA_COLOR_ATTACHMENT0 = GL_COLOR_ATTACHMENT0,
        FBA_COLOR_ATTACHMENT1 = GL_COLOR_ATTACHMENT1,
        FBA_COLOR_ATTACHMENT2 = GL_COLOR_ATTACHMENT2,
        FBA_COLOR_ATTACHMENT3 = GL_COLOR_ATTACHMENT3,
        FBA_COLOR_ATTACHMENT4 = GL_COLOR_ATTACHMENT4,
        FBA_COLOR_ATTACHMENT5 = GL_COLOR_ATTACHMENT5,
        FBA_COLOR_ATTACHMENT6 = GL_COLOR_ATTACHMENT6,
        FBA_COLOR_ATTACHMENT7 = GL_COLOR_ATTACHMENT7,
        FBA_COLOR_ATTACHMENT8 = GL_COLOR_ATTACHMENT8,
        FBA_COLOR_ATTACHMENT9 = GL_COLOR_ATTACHMENT9,
        FBA_COLOR_ATTACHMENT10 = GL_COLOR_ATTACHMENT10,
        FBA_COLOR_ATTACHMENT11 = GL_COLOR_ATTACHMENT11,
        FBA_COLOR_ATTACHMENT12 = GL_COLOR_ATTACHMENT12,
        FBA_COLOR_ATTACHMENT13 = GL_COLOR_ATTACHMENT13,
        FBA_COLOR_ATTACHMENT14 = GL_COLOR_ATTACHMENT14,
        FBA_COLOR_ATTACHMENT15 = GL_COLOR_ATTACHMENT15,
        FBA_DEPTH_ATTACHMENT = GL_DEPTH_ATTACHMENT,
        FBA_STENCIL_ATTACHMENT = GL_STENCIL_ATTACHMENT,
        FBA_DEPTH_STENCIL_ATTACHMENT = GL_DEPTH_STENCIL_ATTACHMENT,
    };
public:
    Framebuffer();
    ~Framebuffer();

    void Bind(FramebufferTarget target);
    void Texture2D(FramebufferTarget target, FramebufferAttachment attachment, Texture* texture, GLint level);

private:
    GLuint mFBO;
};

NS_GLH_END